### ISSUE TITLE
Aggregate Roots as JSON have an artificial `new` attribute

### ISSUE THREAD

**Issue by dschulten** [xmolecules/jmolecules-integrations#296]
The fact that _jmolecules-jackson_ flattens `Identity` wrappers on JSON representations of aggregate roots seems to be intended for situations where you want to hand out your aggregate root entities via ReST without mapping them to a DTO (e.g. because you control the client). However, at least with _spring-data-jdbc_ the JSON response then also has an artificial boolean `new` attribute, which seems to be a byte-buddy generated attribute for INSERT/UPDATE detection.

To expose such an internal `new` attribute via JSON doesn't feel right, although I can suppress it using `@JsonIgnoreProperties("new")` on the aggregate root. Have I found a bug?

**Comment by odrotbohm** [comment]
> seems to be intended for situations where you want to hand out your aggregate root entities via ReST without mapping them to a DTO (e.g. because you control the client).

No. If that was the goal, there'd be Jackson integration for `AggregateRoot`, not only `Identifier` and `Value` object. I'd advise not to hand aggregate root instances to Jackson without proper extends customization about how Jackson is supposed to handle aggregate-specific concerns, such as relationships to other aggregates etc.

In fact, such “advance customization” exists in the form of Spring Data REST, which makes additional assumptions about how to represent and also handle such relationships because it can build on support to declare controllers etc. The jMolecules Jackson library is focussed on support it provides solely given the jMolecules context only.

**Comment by dschulten** [comment]
Thanks for the clarification.
